export const APP_REGISTER_COMPLETED_GAME = 'APP_REGISTER_COMPLETED_GAME';
export const APP_REQUEST_RENDER = 'APP_REQUEST_RENDER';
export const APP_SET_ERROR = 'APP_SET_ERROR';
export const APP_SET_IS_LOADING = 'APP_SET_IS_LOADING';
