export const GAME_PRESS_BACKSPACE = 'GAME_PRESS_BACKSPACE';
export const GAME_PRESS_CHAR = 'GAME_PRESS_CHAR';
export const GAME_REFRESH_DATA = 'GAME_REFRESH_DATA';
export const GAME_SET_DATA = 'GAME_SET_DATA';
export const GAME_SET_SOLUTION = 'GAME_SET_SOLUTION';
export const GAME_SET_ENTRY = 'GAME_SET_ENTRY';
export const GAME_START_NEW = 'GAME_START_NEW';
export const GAME_SUBMIT_GUESS = 'GAME_SUBMIT_GUESS';
